# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/winlogbeat/index.html
# The log belows are supposed to be found under folder:
# C:\Windows\System32\winevt\Logs
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
    ignore_older: 72h
  - name: System
    ignore_older: 72h
setup.template.enabled: false
setup.dashboards.enabled: false
setup.ilm.enabled: false
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  allow_older_versions: true
  hosts: ["beats-ingester-talentsia.packetai.co:443"]
  protocol: https
  path: /elasticsearch/wlb
  compression_level: 9
  index: "index"
  headers:
    X-PAI-IID: ${X-PAI-IID}
    X-PAI-TOKEN: ${X-PAI-TOKEN}

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_fields:
      fields:
        clusterName: ${CLUSTER_NAME}
      target: fields


